// <auto-generated>
//     Source: TestSO.cs
// </auto-generated>
using CmrGame;

namespace CmrGame.Editor
{
    public class TestAccessor : ConfigAccessor
    {
        public string testStrA => GetString("testStrA", "naruto");

        public string[] textStrArr => GetStringArray("textStrArr");

        public int testInt => GetInt("testInt", 666);

        public bool testBool => GetBool("testBool", true);

        public int[] testIntArr => GetIntArray("testIntArr");

    }
}
