using UnityEngine;
using UnityEditor;
using System;
using System.IO;
using System.Text;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;

namespace CmrGame.Editor
{
    public static class ConfigToolkit
    {
        private const char ARRAY_SEPARATOR = '|';
        private const string COLUMN_SEPARATOR = "\t";
        private const string VAR_PREFIX = "#Var";

        /// <summary>
        /// 获取生成的 Accessor 脚本绝对路径
        /// 规则: Assets/Game/{Session}/Scripts/Config/Accessor/{Name}Accessor.cs
        /// </summary>
        public static string GetAccessorPath(ConfigSOBase so)
        {
            string sessionName = so.BelongSession.ToString();
            string className = so.GetType().Name;
            string accessorName = className.EndsWith("SO") ? className.Replace("SO", "Accessor") : className + "Accessor";

            // 拼接路径
            return $"Assets/Game/{sessionName}/Scripts/Config/Accessor/{accessorName}.cs";
        }

        /// <summary>
        /// 获取导出的 TXT 数据绝对路径
        /// 规则: Assets/Game/{Session}/Res/Config/{RelativePath}.txt
        /// </summary>
        public static string GetDataPath(ConfigSOBase so)
        {
            string sessionName = so.BelongSession.ToString();

            // 这里的 Config 名字默认和 SO 名字一致，或者你可以加个字段自定义文件名
            string fileName = so.name; // 使用资源名 (LobbyConfigSO)

            // 对应: Assets/Game/{E_GameSession}/Res/Config/{fileName}.txt
            return $"Assets/Game/{sessionName}/Res/Config/{fileName}.txt";
        }

        // =========================================================
        // 功能 1: 生成 Accessor 代码
        // =========================================================
        public static void GenerateAccessor(ConfigSOBase so)
        {
            string outputPath = GetAccessorPath(so);
            EnsureDirectoryExists(outputPath); // 确保文件夹存在

            string accessorName = Path.GetFileNameWithoutExtension(outputPath);
            // 命名空间建议跟随 Session，例如 CmrGame.Lobby
            string namespaceName = $"CmrGame.{so.BelongSession}";

            StringBuilder sb = new StringBuilder();

            // --- 构建代码内容 ---
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"//     Source: {so.GetType().Name}.cs");
            sb.AppendLine($"//     Session: {so.BelongSession}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using CmrGame;");
            sb.AppendLine();

            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public class {accessorName} : ConfigAccessor");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {accessorName}(ConfigAgent agent, string groupName) : base(agent, groupName) {{ }}");
            sb.AppendLine();

            // --- 遍历字段 ---
            FieldInfo[] fields = so.GetType().GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);

            foreach (var field in fields)
            {
                string typeName = GetTypeName(field.FieldType);
                string method = GetMethodName(field.FieldType);
                string fieldName = field.Name;
                object defaultVal = field.GetValue(so);
                string defaultStr = FormatValue(defaultVal);

                if (method != null)
                {
                    // 数组不需要默认值参数
                    if (field.FieldType.IsArray)
                        sb.AppendLine($"        public {typeName} {fieldName} => {method}(\"{fieldName}\");");
                    else
                        sb.AppendLine($"        public {typeName} {fieldName} => {method}(\"{fieldName}\", {defaultStr});");
                }
                else
                {
                    sb.AppendLine($"        // [Ignored] Unsupported type: {typeName} {fieldName}");
                }
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            try
            {
                File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
                AssetDatabase.Refresh();
                Debug.Log($"<color=green>[ConfigToolkit]</color> Accessor Generated:\n{outputPath}");
            }
            catch (Exception e)
            {
                Debug.LogError($"[ConfigToolkit] Generate Failed: {e.Message}");
            }
        }

        // =========================================================
        // 功能 2: 导出数据
        // =========================================================
        public static void ExportData(ConfigSOBase so)
        {
            string savePath = GetDataPath(so);
            EnsureDirectoryExists(savePath);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine($"# Config Exported from {so.name} ({so.BelongSession})");
            sb.AppendLine($"# Field \t Key \t Type \t Value");

            FieldInfo[] fields = so.GetType().GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);

            foreach (var field in fields)
            {
                object value = field.GetValue(so);
                string valueStr = ConvertObjectToString(value, field.FieldType);

                if (valueStr == null) continue;

                sb.AppendLine($"{VAR_PREFIX}{COLUMN_SEPARATOR}{field.Name}{COLUMN_SEPARATOR}{field.FieldType.Name}{COLUMN_SEPARATOR}{valueStr}");
            }

            try
            {
                File.WriteAllText(savePath, sb.ToString(), Encoding.UTF8);
                AssetDatabase.Refresh();
                Debug.Log($"<color=green>[ConfigToolkit]</color> Exported Data:\n{savePath}");
            }
            catch (Exception e)
            {
                Debug.LogError($"[ConfigToolkit] Export Failed: {e.Message}");
            }
        }

        // =========================================================
        // 功能 3: 导入数据
        // =========================================================
        public static void ImportData(ConfigSOBase so)
        {
            string txtPath = GetDataPath(so);
            if (!File.Exists(txtPath))
            {
                Debug.LogError($"[ConfigToolkit] File not found: {txtPath}");
                return;
            }

            Undo.RecordObject(so, "Import Config");
            string[] lines = File.ReadAllLines(txtPath, Encoding.UTF8);
            Type soType = so.GetType();
            int count = 0;

            foreach (string line in lines)
            {
                if (!line.StartsWith(VAR_PREFIX)) continue;
                string[] parts = line.Split(new string[] { COLUMN_SEPARATOR }, StringSplitOptions.None);
                if (parts.Length < 4) continue;

                string key = parts[1];
                string valStr = parts[3];

                FieldInfo field = soType.GetField(key);
                if (field != null)
                {
                    try
                    {
                        object val = ConvertStringToObject(valStr, field.FieldType);
                        field.SetValue(so, val);
                        count++;
                    }
                    catch { }
                }
            }

            EditorUtility.SetDirty(so);
            AssetDatabase.SaveAssets();
            Debug.Log($"<color=green>[ConfigToolkit]</color> Imported {count} fields from {txtPath}");
        }

        // =========================================================
        // 辅助方法
        // =========================================================
        private static void EnsureDirectoryExists(string assetPath)
        {
            string dir = Path.GetDirectoryName(assetPath);
            if (!Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }
        }

        // ... GetTypeName, GetMethodName, FormatValue, ConvertObjectToString, ConvertStringToObject ...
        // (这些保持上一版代码不变，此处省略以节省篇幅，请直接复用上一版) ...

        // 补全上一版省略的Convert等方法（确保复制时完整）
        private static string GetTypeName(Type type)
        {
            if (type == typeof(int)) return "int";
            if (type == typeof(float)) return "float";
            if (type == typeof(string)) return "string";
            if (type == typeof(bool)) return "bool";
            if (type == typeof(int[])) return "int[]";
            if (type == typeof(float[])) return "float[]";
            if (type == typeof(string[])) return "string[]";
            if (type == typeof(bool[])) return "bool[]";
            return type.Name;
        }

        private static string GetMethodName(Type type)
        {
            if (type == typeof(int)) return "GetInt";
            if (type == typeof(float)) return "GetFloat";
            if (type == typeof(string)) return "GetString";
            if (type == typeof(bool)) return "GetBool";
            if (type == typeof(int[])) return "GetIntArray";
            if (type == typeof(float[])) return "GetFloatArray";
            if (type == typeof(string[])) return "GetStringArray";
            if (type == typeof(bool[])) return "GetBoolArray";
            return null;
        }

        private static string FormatValue(object value)
        {
            if (value == null) return "null";
            if (value is bool b) return b.ToString().ToLower();
            if (value is string s) return $"\"{s}\"";
            if (value is float f) return $"{f}f";
            return value.ToString();
        }

        private static string ConvertObjectToString(object value, Type type)
        {
            if (value == null) return "";
            if (type == typeof(int) || type == typeof(float) || type == typeof(bool) || type == typeof(string))
                return value.ToString();
            if (type.IsArray)
            {
                IList list = value as IList;
                if (list == null) return "";
                List<string> strList = new List<string>();
                foreach (var item in list) strList.Add(item.ToString());
                return string.Join(ARRAY_SEPARATOR.ToString(), strList);
            }
            return null;
        }

        private static object ConvertStringToObject(string value, Type targetType)
        {
            if (targetType == typeof(int)) return int.Parse(value);
            if (targetType == typeof(float)) return float.Parse(value);
            if (targetType == typeof(bool)) return bool.Parse(value);
            if (targetType == typeof(string)) return value;
            if (targetType.IsArray)
            {
                if (string.IsNullOrEmpty(value)) return Array.CreateInstance(targetType.GetElementType(), 0);
                string[] parts = value.Split(ARRAY_SEPARATOR);
                Type elementType = targetType.GetElementType();
                Array array = Array.CreateInstance(elementType, parts.Length);
                for (int i = 0; i < parts.Length; i++)
                {
                    object elementVal = null;
                    if (elementType == typeof(int)) elementVal = int.Parse(parts[i]);
                    else if (elementType == typeof(float)) elementVal = float.Parse(parts[i]);
                    else if (elementType == typeof(bool)) elementVal = bool.Parse(parts[i]);
                    else if (elementType == typeof(string)) elementVal = parts[i];
                    array.SetValue(elementVal, i);
                }
                return array;
            }
            return null;
        }
    }
}